Build_task:
  container:
    image: gradle:4.10.3
  gradle_cache:
    folder: ~/.gradle/caches
    fingerprint_script:
      - cat build.gradle
      - cat settings.gradle
    populate_script: gradle setupCiWorkspace
  script: gradle build
  jar_artifacts:
    path: ./build/libs/*.jar
    type: application/java-archive
  cleanup_before_cache_script:
    - rm -rf ~/.gradle/caches/$GRADLE_VERSION/ ~/.gradle/caches/transforms-1 ~/.gradle/caches/journal-1 ~/.gradle/caches/minecraft/deobfedDeps/compileDummy.jar ~/.gradle/caches/minecraft/deobfedDeps/providedDummy.jar
    - find ~/.gradle/caches/ -name "*.lock" -type f -delete
